app = 'next-gear-motors'
primary_region = 'lhr'
kill_signal = 'SIGTERM'

[build]
image = "registry.fly.io/next-gear-motors:latest"

[env]
PHX_HOST = 'nextgearmotors.ie'
PORT = '4000'
ECTO_IPV6 = 'true'
ERL_AFLAGS = '-proto_dist inet6_tcp'
ELIXIR_ERL_OPTIONS = "+fnu"
AWS_ENDPOINT_URL_S3 = "https://weathered-butterfly-4548.fly.storage.tigris.dev"
AWS_REGION = "auto"
BUCKET_NAME = "weathered-butterfly-4548"
SMTP_RELAY = "smtp.zoho.eu"
SMTP_EMAIL = "nextgearmotors@zohomail.eu"
SMTP_PORT = "465"

[http_service]
internal_port = 4000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[http_service.concurrency]
type = 'connections'
hard_limit = 1000
soft_limit = 1000

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
